name: Golangci-lint
uses: golangci/golangci-lint-action@v6.1.0

on:
    pull_request:
    # Run when a PR is opened, updated, or reopened
        types: [opened, synchronize, reopened]

permissions:
    contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
    golangci:
        name: golang lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: stable
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                  version: v1.60